### ISSUE TITLE
ComputeCpp-Version.props not found

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/LPGPU2-CodeXL#3]
HI Developer,

When installing CodeXL on Windows 7, the ".props" file is not found when running the following script.  Thanks for your help!

"Go to the folder Common/Lib/Ext/ComputeCpp and execute the script SetupComputeCpp.bat.
This will generate the file **ComputeCpp-Version.props**, which is required by the project LPGPU2SyclInfo."

**Comment by mcleary** [comment]
It seems I made a mistake in the initial push and `.gitignore` was not configured properly.
I just added the missing `.prop` files and now `SetupCompute.bat` should have no problems configuring ComputeCpp.

Please check commit: https://github.com/codeplaysoftware/LPGPU2-CodeXL/commit/f9e6846e6c193cd5543343cd0a9369da7acfe10c

**Comment by mcleary** [comment]
I am closing the issue for now. If the provided solution doesn't work please reopen this.
