### ISSUE TITLE
Most drivers depend on this project "WinDriverUtils",Can you tell me where the project is?

### ISSUE THREAD

**Issue by lantaoxu** [codeplaysoftware/LPGPU2-CodeXL#4]
"WinDriverUtils" not found.

**Comment by mcleary** [comment]
Could you please elaborate a little bit more?

Are you trying to build from source? If so, which project is failing to build?

Are you trying one of our release packages?

**Comment by lantaoxu** [comment]
Thanks for your reply.
I didn't build the whole project from source, I just read part of the code.
I am very interested in this project，Especially Windows Kernel Driver。
in this file
https://github.com/codeplaysoftware/LPGPU2-CodeXL/blob/master/Common/Src/WinDriverStackWalker/Src/StackTraceDispatcher.cpp
drivers depend on this project "WinDriverUtils" ,  "<WinDriverUtils\Include\Dpc.hpp>"
but "https://github.com/codeplaysoftware/LPGPU2-CodeXL/tree/master/Common/Src/WinDriverUtils"
not exist。

**Comment by mcleary** [comment]
If you take a look into the Visual Studio project you will notice that this particular file `StackTraceDispatcher.cpp` is not included in the build process, therefore it is ignored by the build system.

Unfortunately, we didn't touch the part of the source code during development of the LPGPU2 project. I suggest you look into the original [source code for CodeXL](https://github.com/GPUOpen-Tools/CodeXL) if you want more details on these sections.

**Comment by lantaoxu** [comment]
Thanks for your reply. Maybe "WinDriverUtils" is not open source.
